version: 2.1

orbs:
  terraform: circleci/terraform@2.1.0

jobs:
  lambda_packaging:
    docker:
      - image: cimg/base:2021.07
    steps:
      - checkout
      - run:
          name: Package S3 to SQS Lambda
          command: zip -r lambda_s3_to_sqs.zip lambda_s3_to_sqs
      - persist_to_workspace:
          root: .
          paths:
            - lambda_s3_to_sqs.zip

  infra_creation:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
            echo 'export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION' >> $BASH_ENV
      - checkout
      - attach_workspace:
          at: .
      - run:
          name: Listing files
          command: ls -l
      - terraform/install
      - terraform/apply:
          backend_config: "bucket=$S3_NAME, key=$S3_KEY"

workflows:
  workflow:
    jobs:
      - lambda_packaging
      - infra_creation:
          requires:
            - lambda_packaging
