version: 2.1

orbs:
  terraform: circleci/terraform@2.1.0

jobs:
  infra_creation:
    docker:
      - image: cimg/base:2021.07
    steps:
      - run:
          name: Update PATH and Define Environment Variable at Runtime
          command: |
            echo 'export AWS_ACCESS_KEY_ID=$AWS_ACCESS_KEY_ID' >> $BASH_ENV
            echo 'export AWS_SECRET_ACCESS_KEY=$AWS_SECRET_ACCESS_KEY' >> $BASH_ENV
            echo 'export AWS_DEFAULT_REGION=$AWS_DEFAULT_REGION' >> $BASH_ENV
      - checkout
      - terraform/install
      - terraform/apply:
          backend_config: "bucket=$S3_NAME, key=$S3_KEY"

workflows:
  workflow:
    jobs:
      - infra_creation
